PoliceAdmin/Models/Rules.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PoliceAdmin.Models
{
    public class RULES
    {
        [Key]
        public int RuleId { get; set; }
        public string Rule { get; set; }
               public int Fine { get; set; }
        public virtual Challan challan { get; set; }
    }
}

PoliceAdmin/Controllers/PUCsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PoliceAdmin.Models;

namespace PoliceAdmin.Controllers
{
    [RoutePrefix("Admin/PUC")]
    public class PUCsController : Controller
    {
        private Universal db = new Universal();

        // GET: PUCs
        [Route("")]
        public ActionResult Index()
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    ViewBag.totalPUC = db.PUCs.ToList().Count();
                    return View(db.PUCs.ToList());
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }

           
        }

        // GET: PUCs/Details/5
        [Route("Details/{id}")]
        public ActionResult Details(string id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    PUC pUC = db.PUCs.Find(id);
                    if (pUC == null)
                    {
                        return HttpNotFound();
                    }
                    return View(pUC);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
           
        }

        // GET: PUCs/Create
        [Route("Create")]
        public ActionResult Create()
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    ViewBag.VehNo = new SelectList(db.Rcs, "VehicleNo", "VehicleNo");
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
          
        }

        // POST: PUCs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Route("Create")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IssueDate,CO,HC")] PUC pUC, string VehNo)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (ModelState.IsValid)
                    {
                        Random r = new Random();
                        RC trc = db.Rcs.Where(m => m.VehicleNo.Equals(VehNo)).FirstOrDefault();
                        var ti = trc.puc;
                        if (ti != null)
                        {
                            string tpucid = ti.PUCNo;
                            PUC p = db.PUCs.Find(tpucid);
                            db.PUCs.Remove(p);
                        }

                        pUC.rc = db.Rcs.Where(m => m.VehicleNo.Equals(VehNo)).ToList();
                        pUC.ExpiryDate = pUC.IssueDate.AddYears(1);
                        pUC.PUCNo = "PUC" + DateTime.Now.GetHashCode().ToString() + VehNo.Substring(4) + r.Next(10000).ToString("D4");
                        db.PUCs.Add(pUC);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }

                    ViewBag.VehNo = new SelectList(db.Rcs, "VehicleNo", "VehicleNo");

                    return View(pUC);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
           
        }



        // GET: PUCs/Delete/5
        [Route("Delete/{id}")]
        public ActionResult Delete(string id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    PUC pUC = db.PUCs.Find(id);
                    if (pUC == null)
                    {
                        return HttpNotFound();
                    }
                    return View(pUC);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
           
        }

        // POST: PUCs/Delete/5
        [Route("Delete/{id}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    PUC pUC = db.PUCs.Find(id);
                    db.PUCs.Remove(pUC);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
           
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PoliceAdmin/Controllers/RULESController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PoliceAdmin.Models;

namespace PoliceAdmin.Controllers
{
    [RoutePrefix("Admin/Rules")]
    public class RULESController : Controller
    {
        private Universal db = new Universal();

        // GET: RULES
        [Route("")]
        public ActionResult Index()
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {

                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    return View(db.RULESs.ToList());
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");
                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");
            }
            
        }

        // GET: RULES/Details/5
        [Route("Details/{id}")]
        public ActionResult Details(int? id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {

                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    RULES rULES = db.RULESs.Find(id);
                    if (rULES == null)
                    {
                        return HttpNotFound();
                    }
                    return View(rULES);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");
                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");
            }
           
        }

        // GET: RULES/Create
        [Route("Create")]
        public ActionResult Create()
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {

                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");
                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");
            }
            
        }

        // POST: RULES/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Create")]
        public ActionResult Create([Bind(Include = "RuleId,Rule,Fine")] RULES rULES)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {

                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (ModelState.IsValid)
                    {
                        db.RULESs.Add(rULES);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }

                    return View(rULES);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");
                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");
            }
           
        }
        [Route("Edit/{id}")]
        // GET: RULES/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {

                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    RULES rULES = db.RULESs.Find(id);
                    if (rULES == null)
                    {
                        return HttpNotFound();
                    }
                    return View(rULES);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");
                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");
            }
           
        }

        // POST: RULES/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Route("Edit/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RuleId,Rule,Fine")] RULES rULES)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {

                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (ModelState.IsValid)
                    {
                        db.Entry(rULES).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    return View(rULES);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");
                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");
            }
           
        }

        // GET: RULES/Delete/5
        [Route("Delete/{id}")]
        public ActionResult Delete(int? id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {

                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    RULES rULES = db.RULESs.Find(id);
                    if (rULES == null)
                    {
                        return HttpNotFound();
                    }
                    return View(rULES);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");
                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");
            }
           
        }

        // POST: RULES/Delete/5
        [Route("Delete/{id}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {

                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    RULES rULES = db.RULESs.Find(id);
                    db.RULESs.Remove(rULES);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");
                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");
            }
           
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PoliceAdmin/Views/RULES/Create.cshtml
@model PoliceAdmin.Models.RULES

@{
    ViewBag.Title = "Create";
}
@section nav{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "TPHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("PUC", "index", "PUCs")</li>
                    <li>@Html.ActionLink("RC BOOK", "index", "RCs")</li>
                    <li>@Html.ActionLink("DL", "index", "DLs")</li>
                    <li>@Html.ActionLink("TraficPolice", "index", "Admin")</li>
                    <li>@Html.ActionLink("Rules", "index", "RULES")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "TrafficLogin")</li>
                </ul>


            </div>
        </div>
    </div>
}
<h2>Create</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RULES</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Rule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rule, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rule, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fine, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PoliceAdmin/Views/RULES/Delete.cshtml
@model PoliceAdmin.Models.RULES

@{
    ViewBag.Title = "Delete";
}
@section nav{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "TPHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("PUC", "index", "PUCs")</li>
                    <li>@Html.ActionLink("RC BOOK", "index", "RCs")</li>
                    <li>@Html.ActionLink("DL", "index", "DLs")</li>
                    <li>@Html.ActionLink("TraficPolice", "index", "Admin")</li>
                    <li>@Html.ActionLink("Rules", "index", "RULES")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "TrafficLogin")</li>
                </ul>


            </div>
        </div>
    </div>
}
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RULES</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rule)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fine)
        </dd>

    </dl>

    @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PoliceAdmin/Views/RULES/Details.cshtml
@model PoliceAdmin.Models.RULES

@{
    ViewBag.Title = "Details";
}
@section nav{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "TPHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("PUC", "index", "PUCs")</li>
                    <li>@Html.ActionLink("RC BOOK", "index", "RCs")</li>
                    <li>@Html.ActionLink("DL", "index", "DLs")</li>
                    <li>@Html.ActionLink("TraficPolice", "index", "Admin")</li>
                    <li>@Html.ActionLink("Rules", "index", "RULES")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "TrafficLogin")</li>
                </ul>


            </div>
        </div>
    </div>
}
<h2>Details</h2>

<div>
    <h4>RULES</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rule)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fine)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RuleId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PoliceAdmin/Views/RULES/Edit.cshtml
@model PoliceAdmin.Models.RULES

@{
    ViewBag.Title = "Edit";
}
@section nav{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "TPHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("PUC", "index", "PUCs")</li>
                    <li>@Html.ActionLink("RC BOOK", "index", "RCs")</li>
                    <li>@Html.ActionLink("DL", "index", "DLs")</li>
                    <li>@Html.ActionLink("TraficPolice", "index", "Admin")</li>
                    <li>@Html.ActionLink("Rules", "index", "RULES")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "TrafficLogin")</li>
                </ul>


            </div>
        </div>
    </div>
}
<h2>Edit</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RULES</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RuleId)

        <div class="form-group">
            @Html.LabelFor(model => model.Rule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rule, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rule, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fine, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PoliceAdmin/Views/RULES/Index.cshtml
@model IEnumerable<PoliceAdmin.Models.RULES>

@{
    ViewBag.Title = "Index";
}
@section nav{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "TPHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("PUC", "index", "PUCs")</li>
                    <li>@Html.ActionLink("RC BOOK", "index", "RCs")</li>
                    <li>@Html.ActionLink("DL", "index", "DLs")</li>
                    <li>@Html.ActionLink("TraficPolice", "index", "Admin")</li>
                    <li>@Html.ActionLink("Rules", "index", "RULES")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "TrafficLogin")</li>
                </ul>


            </div>
        </div>
    </div>
}
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Rule)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fine)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Rule)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fine)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.RuleId }) |
            @Html.ActionLink("Details", "Details", new { id=item.RuleId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.RuleId })
        </td>
    </tr>
}

</table>