PoliceAdmin/Controllers/PUCsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PoliceAdmin.Models;

namespace PoliceAdmin.Controllers
{
    [RoutePrefix("Admin/PUC")]
    public class PUCsController : Controller
    {
        private Universal db = new Universal();

        // GET: PUCs
        [Route("")]
        public ActionResult Index()
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    ViewBag.totalPUC = db.PUCs.ToList().Count();
                    return View(db.PUCs.ToList());
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }

           
        }

        // GET: PUCs/Details/5
        [Route("Details/{id}")]
        public ActionResult Details(string id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    PUC pUC = db.PUCs.Find(id);
                    if (pUC == null)
                    {
                        return HttpNotFound();
                    }
                    return View(pUC);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
           
        }

        // GET: PUCs/Create
        [Route("Create")]
        public ActionResult Create()
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    ViewBag.VehNo = new SelectList(db.Rcs, "VehicleNo", "VehicleNo");
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
          
        }

        // POST: PUCs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Route("Create")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IssueDate,CO,HC")] PUC pUC, string VehNo)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (ModelState.IsValid)
                    {
                        Random r = new Random();
                        RC trc = db.Rcs.Where(m => m.VehicleNo.Equals(VehNo)).FirstOrDefault();
                        var ti = trc.puc;
                        if (ti != null)
                        {
                            string tpucid = ti.PUCNo;
                            PUC p = db.PUCs.Find(tpucid);
                            db.PUCs.Remove(p);
                        }

                        pUC.rc = db.Rcs.Where(m => m.VehicleNo.Equals(VehNo)).ToList();
                        pUC.ExpiryDate = pUC.IssueDate.AddYears(1);
                        pUC.PUCNo = "PUC" + DateTime.Now.GetHashCode().ToString() + VehNo.Substring(4) + r.Next(10000).ToString("D4");
                        db.PUCs.Add(pUC);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }

                    ViewBag.VehNo = new SelectList(db.Rcs, "VehicleNo", "VehicleNo");

                    return View(pUC);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
           
        }



        // GET: PUCs/Delete/5
        [Route("Delete/{id}")]
        public ActionResult Delete(string id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    PUC pUC = db.PUCs.Find(id);
                    if (pUC == null)
                    {
                        return HttpNotFound();
                    }
                    return View(pUC);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
           
        }

        // POST: PUCs/Delete/5
        [Route("Delete/{id}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    PUC pUC = db.PUCs.Find(id);
                    db.PUCs.Remove(pUC);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
           
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PoliceAdmin/Controllers/RCsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PoliceAdmin.Models;

namespace PoliceAdmin.Controllers
{
    [RoutePrefix("Admin/RC")]
    public class RCsController : Controller
    {
        private Universal db = new Universal();
        private ChDL dbc = new ChDL();

        // GET: RCs
        [Route("")]
        public ActionResult Index()
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {

                    var rcs = db.Rcs.Include(r => r.puc);
                    ViewBag.totalRC = rcs.Count();
                    return View(rcs.ToList());
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
           
        }

        // GET: RCs/Details/5
        [Route("Details/{id}")]
        public ActionResult Details(string id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    RC rC = db.Rcs.Find(id);
                    if (rC == null)
                    {
                        return HttpNotFound();
                    }
                    return View(rC);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
           
        }

        // GET: RCs/Create
        [Route("Create")]
        public ActionResult Create()
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    List<SelectListItem> RTOLIST = new List<SelectListItem>();
                    RTOLIST.Add(new SelectListItem { Text = "Surat", Value = "GJ05Surat" });
                    RTOLIST.Add(new SelectListItem { Text = "Ahmedabad", Value = "GJ01Ahmedabad" });
                    RTOLIST.Add(new SelectListItem { Text = "Vadodra", Value = "GJ06Vadodra" });
                    RTOLIST.Add(new SelectListItem { Text = "Amravati", Value = "MH02Amravati" });
                    RTOLIST.Add(new SelectListItem { Text = "Panvel", Value = "MH21Panvel" });
                    RTOLIST.Add(new SelectListItem { Text = "Borivali", Value = "MH22Borivali" });
                    RTOLIST.Add(new SelectListItem { Text = "Udaipur", Value = "RJ01Udaipur" });
                    RTOLIST.Add(new SelectListItem { Text = "Bikaner", Value = "RJ07Bikaner" });
                    RTOLIST.Add(new SelectListItem { Text = "Kota", Value = "RJ20Kota" });

                    List<SelectListItem> VehTypeList = new List<SelectListItem>();
                    VehTypeList.Add(new SelectListItem { Text = "MC50CC", Value = "MC50CCMotorcycles with an engine capacity of 50 cc or less" });
                    VehTypeList.Add(new SelectListItem { Text = "MCWOG", Value = "MCWOG Motorcycles with any engine capacity, but without gears, including mopeds and scooters" });
                    VehTypeList.Add(new SelectListItem { Text = "LMV-NT", Value = "LMV-NTLight motor vehicles that are used for non-transport purposes " });
                    VehTypeList.Add(new SelectListItem { Text = "MCWG", Value = "MCWG  Motorcycles with gear" });

                    ViewBag.VehTypeList = VehTypeList;
                    ViewBag.RTOList = RTOLIST;

                    //ViewBag.VehicleNo = new SelectList(db.PUCs, "PUCNo", "PUCNo");
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }

           
        }

        // POST: RCs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Route("Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OwnerName,RegDate,Vehicletype,RTO,OwnerAddress,AadharNo")] RC rC)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (ModelState.IsValid)
                    {
                        Random r = new Random();
                        System.Text.StringBuilder b = new System.Text.StringBuilder();
                        char ch;
                        ch = Convert.ToChar(Convert.ToInt32(Math.Floor(26 * r.NextDouble() + 65)));
                        b.Append(ch);
                        ch = Convert.ToChar(Convert.ToInt32(Math.Floor(26 * r.NextDouble() + 65)));
                        b.Append(ch);
                        rC.VehicleNo = rC.RTO.Substring(0, 4) + b.ToString().ToUpper() + r.Next(10000).ToString("D4");
                        rC.OwnerName = rC.OwnerName.ToUpper();
                        rC.OwnerAddress = rC.OwnerAddress.ToUpper();
                        rC.ExpiryDate = rC.RegDate.AddYears(10);
                        rC.RTO = "RTO," + rC.RTO.Substring(4).ToUpper();
                        rC.VehicleDescription = rC.Vehicletype.Substring(6).ToUpper();
                        rC.Vehicletype = rC.Vehicletype.Substring(0, 6).Trim().ToUpper();
                        rC.ChasisNo = r.Next(10000000).ToString("D4");
                        rC.EngineNo = r.Next(10000000).ToString("D4");

                        db.Rcs.Add(rC);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }

                    List<SelectListItem> RTOLIST = new List<SelectListItem>();
                    RTOLIST.Add(new SelectListItem { Text = "Surat", Value = "GJ05Surat" });
                    RTOLIST.Add(new SelectListItem { Text = "Ahmedabad", Value = "GJ01Ahmedabad" });
                    RTOLIST.Add(new SelectListItem { Text = "Vadodra", Value = "GJ06Vadodra" });
                    RTOLIST.Add(new SelectListItem { Text = "Amravati", Value = "MH02Amravati" });
                    RTOLIST.Add(new SelectListItem { Text = "Panvel", Value = "MH21Panvel" });
                    RTOLIST.Add(new SelectListItem { Text = "Borivali", Value = "MH22Borivali" });
                    RTOLIST.Add(new SelectListItem { Text = "Udaipur", Value = "RJ01Udaipur" });
                    RTOLIST.Add(new SelectListItem { Text = "Bikaner", Value = "RJ07Bikaner" });
                    RTOLIST.Add(new SelectListItem { Text = "Kota", Value = "RJ20Kota" });

                    List<SelectListItem> VehTypeList = new List<SelectListItem>();
                    VehTypeList.Add(new SelectListItem { Text = "MC50CC", Value = "MC50CCMotorcycles with an engine capacity of 50 cc or less" });
                    VehTypeList.Add(new SelectListItem { Text = "MCWOG", Value = "MCWOG Motorcycles with any engine capacity, but without gears, including mopeds and scooters" });
                    VehTypeList.Add(new SelectListItem { Text = "LMV-NT", Value = "LMV-NTLight motor vehicles that are used for non-transport purposes " });
                    VehTypeList.Add(new SelectListItem { Text = "MCWG", Value = "MCWG  Motorcycles with gear" });

                    ViewBag.VehTypeList = VehTypeList;
                    ViewBag.RTOList = RTOLIST;
                    ViewBag.VehicleNo = new SelectList(db.Challans, "ChallanNo", "ChallanNo", rC.VehicleNo);
                    ViewBag.VehicleNo = new SelectList(db.PUCs, "PUCNo", "PUCNo", rC.VehicleNo);
                    return View(rC);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
            
        }

        // GET: RCs/Edit/5
        [Route("Edit/{id}")]
        public ActionResult Edit(string id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    RC rC = db.Rcs.Find(id);
                    if (rC == null)
                    {
                        return HttpNotFound();
                    }
                    ViewBag.VehicleNo = new SelectList(db.Challans, "ChallanNo", "ChallanNo", rC.VehicleNo);
                    ViewBag.VehicleNo = new SelectList(db.PUCs, "PUCNo", "PUCNo", rC.VehicleNo);
                    return View(rC);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
            
        }

        // POST: RCs/Edit/5

PoliceAdmin/Views/RCs/Create.cshtml
@model PoliceAdmin.Models.RC

@{
    ViewBag.Title = "Create";
}
@section nav{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "TPHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("PUC", "index", "PUCs")</li>
                    <li>@Html.ActionLink("RC BOOK", "index", "RCs")</li>
                    <li>@Html.ActionLink("DL", "index", "DLs")</li>
                    <li>@Html.ActionLink("TraficPolice", "index", "Admin")</li>
                    <li>@Html.ActionLink("Rules", "index", "RULES")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "TrafficLogin")</li>
                </ul>


            </div>
        </div>
    </div>
}
<h2>Create</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RC</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegDate, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Vehicletype, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    ViewBag.Vehicletype = ViewBag.VehTypeList;
                }
                @Html.DropDownList("Vehicletype")


                @Html.ValidationMessageFor(model => model.Vehicletype, "", new { @class = "text-danger" })
            </div>
        </div>






        <div class="form-group">
            @Html.LabelFor(model => model.RTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    ViewBag.RTO = ViewBag.RTOList;
                }
                @Html.DropDownList("RTO")

                @Html.ValidationMessageFor(model => model.RTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnerAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnerAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AadharNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AadharNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AadharNo, "", new { @class = "text-danger" })
            </div>
        </div>
      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PoliceAdmin/Views/RCs/Delete.cshtml
@model PoliceAdmin.Models.RC

@{
    ViewBag.Title = "Delete";
}
@section nav{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "TPHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("PUC", "index", "PUCs")</li>
                    <li>@Html.ActionLink("RC BOOK", "index", "RCs")</li>
                    <li>@Html.ActionLink("DL", "index", "DLs")</li>
                    <li>@Html.ActionLink("TraficPolice", "index", "Admin")</li>
                    <li>@Html.ActionLink("Rules", "index", "RULES")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "TrafficLogin")</li>
                </ul>


            </div>
        </div>
    </div>
}
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RC</h4>
    <hr />
    <dl class="dl-horizontal">
     
            @Html.DisplayNameFor(model => model.puc.PUCNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.puc.PUCNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpiryDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vehicletype)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vehicletype)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VehicleDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChasisNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChasisNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EngineNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EngineNo)
        </dd>

      
    </dl>

    @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" })) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PoliceAdmin/Views/RCs/Details.cshtml
@model PoliceAdmin.Models.RC

@{
    ViewBag.Title = "Details";
}
@section nav{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "TPHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("PUC", "index", "PUCs")</li>
                    <li>@Html.ActionLink("RC BOOK", "index", "RCs")</li>
                    <li>@Html.ActionLink("DL", "index", "DLs")</li>
                    <li>@Html.ActionLink("TraficPolice", "index", "Admin")</li>
                    <li>@Html.ActionLink("Rules", "index", "RULES")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "TrafficLogin")</li>
                </ul>


            </div>
        </div>
    </div>
}
<h2>Details</h2>

<div>
    <h4>RC</h4>
    <hr />
    <dl class="dl-horizontal">
       
     
        <dt>
            @Html.DisplayNameFor(model => model.OwnerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpiryDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vehicletype)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vehicletype)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VehicleDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChasisNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChasisNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EngineNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EngineNo)
        </dd>

     
       
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VehicleNo }) |@Html.ActionLink("Delete", "Delete", new { id = Model.VehicleNo })|
    @Html.ActionLink("Back to List", "Index")
</p>