PoliceAdmin/Controllers/DLsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PoliceAdmin.Models;

namespace PoliceAdmin.Controllers
{
    [RoutePrefix("Admin/DL")]
    public class DLsController : Controller
    {
        private Universal db = new Universal();
        private ChDL dbc = new ChDL();
        // GET: DLs
        [Route("")]
        public ActionResult Index()
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    ViewBag.totalDL = db.DLs.ToList().Count();
                    return View(db.DLs.ToList());
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
        }   

        // GET: DLs/Details/5
        [Route("Details/{id}")]
        public ActionResult Details(string id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {

                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    DL dL = db.DLs.Find(id);
                    if (dL == null)
                    {
                        return HttpNotFound();
                    }
                    return View(dL);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");
            }

        
        }

        // GET: DLs/Create
        [Route("Create")]
        public ActionResult Create()
        {
            List<SelectListItem> RTOLIST = new List<SelectListItem>();
            RTOLIST.Add(new SelectListItem { Text = "Surat", Value = "GJ05Surat" });
            RTOLIST.Add(new SelectListItem { Text = "Ahmedabad", Value = "GJ01Ahmedabad" });
            RTOLIST.Add(new SelectListItem { Text = "Vadodra", Value = "GJ06Vadodra" });
            RTOLIST.Add(new SelectListItem { Text = "Amravati", Value = "MH02Amravati" });
            RTOLIST.Add(new SelectListItem { Text = "Panvel", Value = "MH21Panvel" });
            RTOLIST.Add(new SelectListItem { Text = "Borivali", Value = "MH22Borivali" });
            RTOLIST.Add(new SelectListItem { Text = "Udaipur", Value = "RJ01Udaipur" });
            RTOLIST.Add(new SelectListItem { Text = "Bikaner", Value = "RJ07Bikaner" });
            RTOLIST.Add(new SelectListItem { Text = "Kota", Value = "RJ20Kota" });

            List<SelectListItem> VehTypeList = new List<SelectListItem>();
            VehTypeList.Add(new SelectListItem { Text = "MC50CC", Value = "MC50CCMotorcycles with an engine capacity of 50 cc or less" });
            VehTypeList.Add(new SelectListItem { Text = "MCWOG", Value = "MCWOG Motorcycles with any engine capacity, but without gears, including mopeds and scooters" });
            VehTypeList.Add(new SelectListItem { Text = "LMV-NT", Value = "LMV-NTLight motor vehicles that are used for non-transport purposes " });
            VehTypeList.Add(new SelectListItem { Text = "MCWG", Value = "MCWG  Motorcycles with gear" });


            if (Request.Cookies.Get("tAdmin") != null)
            {
                
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    ViewBag.VehTypeList = VehTypeList;
                    ViewBag.RTOList = RTOLIST;
                    ViewBag.LicenceNo = new SelectList(db.Challans, "ChallanNo", "ChallanNo");
                    ViewBag.PublicUserId = new SelectList(db.pus, "PublicUserId", "UserName");
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");
                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");
            }
            
        }

        // POST: DLs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Route("Create")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OwnerName,IssueDate,OwnerAddress,DOB,RTO,Vehicletype,AadharNo")] DL dL, HttpPostedFileBase profilepic)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {

                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (ModelState.IsValid)
                    {
                        if (profilepic != null)
                        {
                            if (profilepic.ContentType == "image/jpg" || profilepic.ContentType == "image/jpeg" || profilepic.ContentType == "image/png")
                            {
                                string ext = System.IO.Path.GetExtension(profilepic.FileName);
                                int num = db.DLs.ToArray().Length + 1;
                                dL.LicenceNo = dL.RTO.Substring(0, 4) + " " + dL.IssueDate.Year + "00" + num;
                                profilepic.SaveAs(Server.MapPath("/") + "/Content/DrivingLicence/" + dL.LicenceNo + ext);
                                dL.profilepic = dL.LicenceNo + ext;
                            }
                            else
                            {
                                TempData["ErrorMsg"] = "image must be in formate of jpg/png/jpeg only";
                                return RedirectToAction("Create");
                            }
                        }
                       
                        dL.OwnerName = dL.OwnerName.ToUpper();
                        dL.ExpiryDate = dL.IssueDate.AddYears(10);
                        dL.VehicleDescription = dL.Vehicletype.Substring(6).ToUpper();
                        dL.Vehicletype = dL.Vehicletype.Substring(0, 6).Trim().ToUpper();
                        dL.RTO = "RTO," + dL.RTO.Substring(4).ToUpper();
                        dL.OwnerAddress = dL.OwnerAddress.ToUpper();


                        db.DLs.Add(dL);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        List<SelectListItem> RTOLIST = new List<SelectListItem>();
                        RTOLIST.Add(new SelectListItem { Text = "Surat", Value = "GJ05Surat" });
                        RTOLIST.Add(new SelectListItem { Text = "Ahmedabad", Value = "GJ01Ahmedabad" });
                        RTOLIST.Add(new SelectListItem { Text = "Vadodra", Value = "GJ06Vadodra" });
                        RTOLIST.Add(new SelectListItem { Text = "Amravati", Value = "MH02Amravati" });
                        RTOLIST.Add(new SelectListItem { Text = "Panvel", Value = "MH21Panvel" });
                        RTOLIST.Add(new SelectListItem { Text = "Borivali", Value = "MH22Borivali" });
                        RTOLIST.Add(new SelectListItem { Text = "Udaipur", Value = "RJ01Udaipur" });
                        RTOLIST.Add(new SelectListItem { Text = "Bikaner", Value = "RJ07Bikaner" });
                        RTOLIST.Add(new SelectListItem { Text = "Kota", Value = "RJ20Kota" });

                        List<SelectListItem> VehTypeList = new List<SelectListItem>();
                        VehTypeList.Add(new SelectListItem { Text = "MC50CC", Value = "MC50CCMotorcycles with an engine capacity of 50 cc or less" });
                        VehTypeList.Add(new SelectListItem { Text = "MCWOG", Value = "MCWOG Motorcycles with any engine capacity, but without gears, including mopeds and scooters" });
                        VehTypeList.Add(new SelectListItem { Text = "LMV-NT", Value = "LMV-NTLight motor vehicles that are used for non-transport purposes " });
                        VehTypeList.Add(new SelectListItem { Text = "MCWG", Value = "MCWG  Motorcycles with gear" });

                        ViewBag.VehTypeList = VehTypeList;
                        ViewBag.RTOList = RTOLIST;
                        return View(dL);
                    }
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");
                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");
            }



        }
        

        // GET: DLs/Edit/5
        [Route("Edit/{id}")]
        public ActionResult Edit(string id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {

                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    DL dL = db.DLs.Find(id);
                    if (dL == null)
                    {
                        return HttpNotFound();
                    }


                    return View(dL);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");
                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

PoliceAdmin/Controllers/PUCsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PoliceAdmin.Models;

namespace PoliceAdmin.Controllers
{
    [RoutePrefix("Admin/PUC")]
    public class PUCsController : Controller
    {
        private Universal db = new Universal();

        // GET: PUCs
        [Route("")]
        public ActionResult Index()
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    ViewBag.totalPUC = db.PUCs.ToList().Count();
                    return View(db.PUCs.ToList());
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }

           
        }

        // GET: PUCs/Details/5
        [Route("Details/{id}")]
        public ActionResult Details(string id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    PUC pUC = db.PUCs.Find(id);
                    if (pUC == null)
                    {
                        return HttpNotFound();
                    }
                    return View(pUC);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
           
        }

        // GET: PUCs/Create
        [Route("Create")]
        public ActionResult Create()
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    ViewBag.VehNo = new SelectList(db.Rcs, "VehicleNo", "VehicleNo");
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
          
        }

        // POST: PUCs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Route("Create")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IssueDate,CO,HC")] PUC pUC, string VehNo)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (ModelState.IsValid)
                    {
                        Random r = new Random();
                        RC trc = db.Rcs.Where(m => m.VehicleNo.Equals(VehNo)).FirstOrDefault();
                        var ti = trc.puc;
                        if (ti != null)
                        {
                            string tpucid = ti.PUCNo;
                            PUC p = db.PUCs.Find(tpucid);
                            db.PUCs.Remove(p);
                        }

                        pUC.rc = db.Rcs.Where(m => m.VehicleNo.Equals(VehNo)).ToList();
                        pUC.ExpiryDate = pUC.IssueDate.AddYears(1);
                        pUC.PUCNo = "PUC" + DateTime.Now.GetHashCode().ToString() + VehNo.Substring(4) + r.Next(10000).ToString("D4");
                        db.PUCs.Add(pUC);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }

                    ViewBag.VehNo = new SelectList(db.Rcs, "VehicleNo", "VehicleNo");

                    return View(pUC);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
           
        }



        // GET: PUCs/Delete/5
        [Route("Delete/{id}")]
        public ActionResult Delete(string id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    PUC pUC = db.PUCs.Find(id);
                    if (pUC == null)
                    {
                        return HttpNotFound();
                    }
                    return View(pUC);
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
           
        }

        // POST: PUCs/Delete/5
        [Route("Delete/{id}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            if (Request.Cookies.Get("tAdmin") != null)
            {
                string t = Request.Cookies.Get("tAdmin").Value;
                if (t == "Yes")
                {
                    PUC pUC = db.PUCs.Find(id);
                    db.PUCs.Remove(pUC);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", "TrafficLogin");

                }
            }
            else
            {
                return RedirectToAction("Index", "TrafficLogin");

            }
           
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PoliceAdmin/Views/Challans/Create.cshtml
@model PoliceAdmin.Models.Challan

@{
    ViewBag.Title = "Create";
}
@section nav{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "TPHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("PUC", "index", "PUCs")</li>
                    <li>@Html.ActionLink("RC BOOK", "index", "RCs")</li>
                    <li>@Html.ActionLink("DL", "index", "DLs")</li>
                    <li>@Html.ActionLink("TraficPolice", "index", "Admin")</li>
                    <li>@Html.ActionLink("Rules", "index", "RULES")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "TrafficLogin")</li>
                </ul>


            </div>
        </div>
    </div>
}
<h2>Create</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Challan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ChallanNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChallanNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChallanNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IssueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IssueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IssueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LicenceNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LicenceNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LicenceNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RCNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RCNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RCNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.totalFine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.totalFine, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.totalFine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Paid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Paid)
                    @Html.ValidationMessageFor(model => model.Paid, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
    @Html.ActionLink("Delete","Delete")
</div>

PoliceAdmin/Views/Challans/Details.cshtml
@model PoliceAdmin.Models.Challan

@{
    ViewBag.Title = "Details";
}
@section nav{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "TPHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("PUC", "index", "PUCs")</li>
                    <li>@Html.ActionLink("RC BOOK", "index", "RCs")</li>
                    <li>@Html.ActionLink("DL", "index", "DLs")</li>
                    <li>@Html.ActionLink("TraficPolice", "index", "Admin")</li>
                    <li>@Html.ActionLink("Rules", "index", "RULES")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "TrafficLogin")</li>
                </ul>


            </div>
        </div>
    </div>
}
<h2>Details</h2>

<div>
    <h4>Challan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IssueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IssueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LicenceNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LicenceNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RCNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RCNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.totalFine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.totalFine)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Paid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Paid)
        </dd>

    </dl>
</div>
<p>
   @Html.ActionLink("Edit", "Edit", new { id = Model.ChallanNo }) |
    @Html.ActionLink("Back to List", "Index")|
    @Html.ActionLink("Delete", "Delete", new { id = Model.ChallanNo } )
</p>

PoliceAdmin/Views/Challans/Edit.cshtml
@model PoliceAdmin.Models.Challan

@{
    ViewBag.Title = "Edit";
}
@section nav{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "TPHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("PUC", "index", "PUCs")</li>
                    <li>@Html.ActionLink("RC BOOK", "index", "RCs")</li>
                    <li>@Html.ActionLink("DL", "index", "DLs")</li>
                    <li>@Html.ActionLink("TraficPolice", "index", "Admin")</li>
                    <li>@Html.ActionLink("Rules", "index", "RULES")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "TrafficLogin")</li>
                </ul>


            </div>
        </div>
    </div>
}
<h2>Edit</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Challan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ChallanNo)

        <div class="form-group">
            @Html.LabelFor(model => model.IssueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IssueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IssueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LicenceNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LicenceNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LicenceNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RCNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RCNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RCNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.totalFine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.totalFine, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.totalFine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Paid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Paid)
                    @Html.ValidationMessageFor(model => model.Paid, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")|
    @Html.ActionLink("Delete","Delete")
</div>

PoliceAdmin/Views/Challans/Index.cshtml
@model IEnumerable<PoliceAdmin.Models.Challan>

@{
    ViewBag.Title = "Index";
}
@section nav{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "TPHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("PUC", "index", "PUCs")</li>
                    <li>@Html.ActionLink("RC BOOK", "index", "RCs")</li>
                    <li>@Html.ActionLink("DL", "index", "DLs")</li>
                    <li>@Html.ActionLink("TraficPolice", "index", "Admin")</li>
                    <li>@Html.ActionLink("Rules", "index", "RULES")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "TrafficLogin")</li>
                </ul>


            </div>
        </div>
    </div>
}
<h2>Index</h2>

<p>

    Total Challans issued:@ViewBag.totalCH<br />

    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IssueDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ChallanNo )
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LicenceNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RCNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.totalFine)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Paid)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IssueDate)
        </td>
        <th>
            @Html.DisplayFor(model => item.ChallanNo)
        </th>

        <td>
            @Html.DisplayFor(modelItem => item.LicenceNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RCNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.totalFine)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Paid)
        </td>
        <td>
            @*Html.ActionLink("Edit", "Edit", new { id=item.ChallanNo }) |*@
            @Html.ActionLink("Details", "Details", new { id=item.ChallanNo }) |
            @* @Html.ActionLink("Delete", "Delete", new { id=item.ChallanNo })*@
            </td>
        </tr>
    }

    </table>